#-*- coding: utf8 -*-

PCC_HOST_PREFIX = "http://cmdweb.pcc.gov.tw"


URL_INFORMATION = {
    "start_login_page": "/pccms/owa/cmdmang.userin",
    "login_page": "/pccms/owa/cmdmang.chkpas",
    "query_project": "/pccms/owa/prjquer.lspridet",
    "fishey_project_list": "/pccms/owa/prjquer.lsprj_2",
    "search_uid": "/pccms/owa/prjquer.querprj",
    "search_page": "/pccms/owa/prjquer.searchprj",
    "project_list": "/pccms/owa/prjquer.lsprj",
    "old_project_list": "/pccms/owa/prjquer.lsprja",
  }

DOCUMENT_PARSER_REFERENCE = {
  'project_document': [
        {'key': u'url_supervise_input',
         'seek': [u'標案資料查詢', u'<table', u'<a href='],
         'until': u'>上級機關品質查核結果輸入'},

        {'key': u'project_name',
         'seek': [u'標案名稱', u'bgcolor=#ffffc7>'],
         'until': u'</td>'},

        {'key': u'project_uid',
         'seek': [u'標案編號</th>', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'construction_type',
         'seek': [u'工程類別</th>', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'implementation_department',
         'seek': [u'執行單位</th>', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'budgetary_sources',
         'seek': [u'預算來源</th>', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'host_department',
         'seek': [u'主辦機關</th>', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'head_department',
         'seek': [u'主管機關', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'manager',
         'seek': [u'聯絡人', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'telphone',
         'seek': [u'聯絡電話', u'#ffffc7>'],
         'until': u'</td>'},

        {'key': u'progress',
         'seek': [u'年/月'],
         'seek_sub': u'href=',
         'sub': [{'key': u'url',
                 'seek': [],
                 'until': u'>'}],
         'terminate': u'</table>'},
          
        {'key': u'url_basic_information',
         'seek': [u'本標案報表列印', u'<a href='],
         'until': u'>基本資料表'},
        
        {'key': u'url_supervise_information',
         'seek': [u'品管人員登錄表' ,u'<a href='],
         'until': u'>查核紀錄表'},

        {'key': u'url_budget_information',
         'seek': [u'<a href='],
         'until': u'>預算核定表'},

  ],
  'project_information':[
        {'key': u'name',
         'seek': [u'標案名稱</font>：'],
         'until': u'</td>'},
         
        {'key': u'implementation_department',
         'seek': [u'執行機關：'],
         'until': u'</td>'},
         
        {'key': u'manager',
         'seek': [u'聯絡人：'],
         'until': u'</td>'},
          
        {'key': u'telphone',
         'seek': [u'聯絡電話：'],
         'until': u'</td>'},
         
        {'key': u'head_department',
         'seek': [u'主管機關：'],
         'until': u'</td>'},
          
        {'key': u'host_department',
         'seek': [u'主辦機關：'],
         'until': u'</td>'},
          
        {'key': u'budget_from',
         'seek': [u'經費來源機關：'],
         'until': u'</td>'},
          
        {'key': u'host_department_code',
         'seek': [u'招標公告單位代碼：'],
         'until': u'</td>'},

        {'key': u'engineering_county',
         'seek': [u'縣市別：'],
         'until': u'</td>'},

        {'key': u'engineering_location',
         'seek': [u'施工地點：'],
         'until': u'</td>'},

        {'key': u'total_budget',
         'seek': [u'工程總預算：'],
         'until': u'</td>'},

        {'key': u'contract_budget',
         'seek': [u'發包預算：'],
         'until': u'</td>'},

        {'key': u'inspector_name',
         'seek': [u'監造單位</font>：'],
         'until': u'</td>'},

        {'key': u'constructor',
         'seek': [u'承造廠商</font>1：'],
         'until': u'</td>'},

        {'key': u's_design_complete_date',
         'seek': [u'預定完成規劃設計日期：'],
         'until': u'</td>'},
          
        {'key': u'r_design_complete_date',
         'seek': [u'實際完成規劃設計日期：'],
         'until': u'</td>'},
          
        {'key': u's_public_date',
         'seek': [u'預定公告日期：<font size=-1 color=gray>'],
         'until': u'</td>'},
          
        {'key': u'r_public_date',
         'seek': [u'實際公告日期：'],
         'until': u'</td>'},
          
        {'key': u's_decide_tenders_date',
         'seek': [u'預定決標日期：'],
         'until': u'</td>'},
          
        {'key': u'r_decide_tenders_date',
         'seek': [u'實際決標日期</font>：'],
         'until': u'</td>'},

        {'key': u's_tenders_method',
         'seek': [u'預定招標方式：'],
         'until': u'</td>'},
          
        {'key': u'r_tenders_method',
         'seek': [u'實際招標方式：'],
         'until': u'</td>'},
          
        {'key': u'decide_tenders_method',
         'seek': [u'決標方式：'],
         'until': u'</td>'},
          
        {'key': u'pay_method',
         'seek': [u'契約費用給付方式：'],
         'until': u'</td>'},
          
        {'key': u's_base_price',
         'seek': [u'預估底價：'],
         'until': u'</td>'},
          
        {'key': u'r_base_price',
         'seek': [u'會核底價：'],
         'until': u'</td>'},
          
        {'key': u'decide_tenders_price',
         'seek': [u'決標金額</font>：'],
         'until': u'千元'},
          
        {'key': u'decide_tenders_price2',
         'seek': [u'變更設計後之契約金額：'],
         'until': u'\)</font>',
         'allow_skip': True},
          
        {'key': u'contract_id',
         'seek': [u'契約編號：'],
         'until': u'</td>'},
          
        {'key': u's_start_date',
         'seek': [u'<font color=blue >預定開工日期</font>：'],
         'until': u'</td>'},
          
        {'key': u'r_start_date',
         'seek': [u'<font color=blue>實際開工日期</font>：'],
         'until': u'</td>'},
          
        {'key': u's_end_date',
         'seek': [u'預定完工日期：'],
         'until': u'日'},
          
        {'key': u's_end_date2',
         'seek': [u'變更後：'],
         'until': u'</td>',
         'allow_skip': True},

        {'key': u'r_end_date',
         'seek': [u'實際完工日期：'],
         'until': u'</td>'},
          
        {'key': u'r_checked_and_accepted_date',
         'seek': [u'實際完成驗收日期：'],
         'until': u'</td>',
         'allow_skip':True},
          
        {'key': u's_last_pay_date',
         'seek': [u'預定決算日期：'],
         'until': u'</td>'},
          
        {'key': u'r_last_pay_date',
         'seek': [u'實際決算日期：'],
         'until': u'</td>'},
          
        {'key': u'balancing_price',
         'seek': [u'結算金額：'],
         'until': u'</td>'},
          
        {'key': u'last_pay_price',
         'seek': [u'決算金額：'],
         'until': u'</td>'}
  ],
  'project_progess':[
        {'key': u'year',
         'seek': [u'預付款', u'colspan=4>'],
         'until': u'年'},
        {'key': u'month',
         'seek': [],
         'until': u'月'},
        {'key': u'percentage_of_predict_progress',
         'seek': [u'年累計預定進度', u'#ffffc7>'],
         'until': u'</td>'},
        {'key': u'percentage_of_real_progress',
         'seek': [u'年累計實際進度', u'#ffffc7>'],
         'until': u'</td>'},
        {'key': u'money_of_predict_progress',
         'seek': [u'年累計預定金額', u'#ffffc7>'],
         'until': u'</td>'},
        {'key': u'money_of_real_progress',
         'seek': [u'年累計實際金額', u'#ffffc7>'],
         'until': u'</td>'},
        {'key': u'totale_money_paid',
         'seek': [u'累計估驗計價金額', u'#ffffc7>'],
         'until': u'</td>'},
        {'key': u'status',
         'seek': [u'執行狀況', u'#ffffc7>'],
         'until': u'</td>'}
  ],
  'supervise_information':[
        {'key': u'subordinate_agencies_unit',
         'seek': [u'工程主管機關', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'date',
         'seek': [u'日期', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'project',
         'seek': [u'標案名稱', u'<a', u'>'],
         'until': u'</a>'},
        {'key': u'place_location',
         'seek': [u'地點', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'project_organizer_agencies',
         'seek': [u'執行機關', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'project_manage_unit',
         'seek': [u'專案管理', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'designer',
         'seek': [u'設計單位', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'inspector',
         'seek': [u'監造單位', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'construct',
         'seek': [u'承包商', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'budget_price',
         'seek': [u'發包預算', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'contract_price',
         'seek': [u'契約金額', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'info',
         'seek': [u'工程概要', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'progress_date',
         'seek': [u'截至'],
         'until': u'止'},
        {'key': u'scheduled_progress',
         'seek': [u'預定'],
         'until': u'；'},
        {'key': u'actual_progress',
         'seek': [u'實際'],
         'until': u'；'},
        {'key': u'scheduled_money',
         'seek': [u'預定'],
         'until': u'；'},
        {'key': u'actual_money',
         'seek': [u'實際'],
         'until': u'。'},
        {'key': u'progress_info',
         'seek': [u'三、'],
         'until': u'</td>'},
        {'key': u'outguide',
         'seek': [u'委員', u'外聘：'],
         'until': u'<'},
        {'key': u'inguide',
         'seek': [u'內聘：'],
         'until': u'</td>'},
        {'key': u'start_date',
         'seek': [u'日期', u'<td', u'font', u'>'],
         'until': u'至'},
        {'key': u'expected_completion_date',
         'seek': [u'<br>'],
         'until': u'</td>'},
        {'key': u'captain',
         'seek': [u'領隊：'],
         'until': u'<'},
        {'key': u'worker',
         'seek': [u'工作人員：'],
         'until': u'</td>'},
        {'key': u'score',
         'seek': [u'查核分數', u'<td', u'>'],
         'until': u'分'},
        {'key': u'merit',
         'seek': [u'優<br>點', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'advise',
         'seek': [u'規劃<br>設計<br>問題<br>及<br>建議', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'other_advise',
         'seek': [u'其<br>他<br>建<br>議', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'deductions',
         'seek': [u'扣<br>點<br>統<br>計', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'test',
         'seek': [u'檢<br>驗<br>拆<br>驗', u'<td', u'>'],
         'until': u'</td>'},
  ],
  'auditing_information':[
        {'key': u'plan',
         'seek': [u'列管計畫名稱', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'manage_unit',
         'seek': [u'工程主管機關', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'date',
         'seek': [u'日期', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'project_name',
         'seek': [u'標案名稱', u'<td' ,u'<a', u'>'],
         'until': u'</a>'},
        {'key': u'location',
         'seek': [u'地點', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'unit',
         'seek': [u'執行機關', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'project_manage_unit',
         'seek': [u'專案管理', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'designer',
         'seek': [u'設計單位', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'inspector',
         'seek': [u'監造單位', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'construct',
         'seek': [u'承包商', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'budget_price',
         'seek': [u'發包預算', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'contract_price',
         'seek': [u'契約金額', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'info',
         'seek': [u'工程概要', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'progress',
         'seek': [u'目前施工概況', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'supervisors_outside',
         'seek': [u'委員', u'外聘：'],
         'until': u'<'},
        {'key': u'supervisors_inside',
         'seek': [u'內聘：'],
         'until': u'<'},
        {'key': u'start_date',
         'seek': [u'日期', u'<td', u'font', u'>'],
         'until': u'至'},
        {'key': u'expected_completion_date',
         'seek': [u'<br>'],
         'until': u'</td>'},
        {'key': u'captain',
         'seek': [u'領隊：'],
         'until': u'<'},
        {'key': u'workers',
         'seek': [u'工作人員：'],
         'until': u'<'},
        {'key': u'score',
         'seek': [u'查核分數', u'<td', u'>'],
         'until': u'分'},
        {'key': u'merit',
         'seek': [u'優<br>點', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'errors',
         'seek': [u'缺<br>點', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'advise',
         'seek': [u'規劃<br>設計<br>問題<br>及<br>建議', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'quality_indicators',
         'seek': [u'品<br>質<br>指<br>標', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'other_advise',
         'seek': [u'其<br>他<br>建<br>議', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'deductions',
         'seek': [u'扣<br>點<br>統<br>計', u'<td', u'>'],
         'until': u'</td>'},
        {'key': u'test',
         'seek': [u'檢<br>驗<br>拆<br>驗', u'<td', u'>'],
         'until': u'</td>'},
  ]
}