#!/bin/bash
root=`dirname ${BASH_SOURCE[0]}`
dir=$1
for i in `find ${root}/${dir} -name "*.mjpg"`;do
    mp4_filename="${i%.mjpg}.mp4"
    /usr/bin/HandBrakeCLI -w 720 -a none -2 -T -e x264 -O --input $i --output $mp4_filename && rm -rf $i
done

exit 0
